source "https://rubygems.org"
gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-activerecord"
gem "rake"
gem "thin"
gem "activerecord"
gem "pg"
gem 'tux', '~> 0.3.0'
gem "pry"
gem "ransack"
gem "rails"
gem "railties"
gem "imgurapi"
